language: java
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - chmod +x gradlew
before_script:
  - sleep 15
script:
  - ./gradlew test
  - ./gradlew test --tests "ua.com.juja.microservices.integration.*"